_auth/urls.py
from django.conf.urls import url

from . import views

app_name = "_auth"

urlpatterns = [
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^signup$', views.SignUp.as_view(), name='signup'),
    url(r'^activate/(?P<hash>.+)$', views.activate_user, name='activate'),

    url(r'^password-reset$', views.Reset.as_view(), name='password-reset'),
    url(r'^confirm-password-reset/(?P<hash>.+)$', views.ConfirmReset.as_view(),
        name='confirm-password-reset')
]

motors/urls.py
from django.conf.urls import url

from . import views

app_name = "motors"

urlpatterns = [
    url(r'^$', views.motors_list, name='motors_list'),
    url(r'^item/(?P<item_pk>\d+)$', views.show_item, name='show_item')
]

shoutboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),

    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1.0/', include(router.urls))

    # Auth in api web view.
    # url(r'^api/v1.0/auth', include("rest_framework.urls",
    #                                  namespace="rest_framework")),

    url(r'^api/v1.0/', include('api_1_0.urls')),
    url(r'^motors/', include('motors.urls')),
    url(r'^auth/', include('_auth.urls')),

    url(r'^profile/', include('_profile.urls'))
]

motors/models.py
from django.db import models
# from urllib.parse import quote
import requests
# from shoutboard.settings import MEDIA_ROOT
from urllib.parse import urlparse
from os.path import splitext, basename
from uuid import uuid4
import os
from django.core.files import File

from requests.exceptions import MissingSchema


# Create your models here.
class Motor(models.Model):

    # Path inside MEDIA_ROOT.
    local_path = 'motors'

    class Meta:
        db_table = "motors"

    title = models.CharField(max_length=200)

    cover_img_url = models.URLField(blank=True)
    description = models.TextField(max_length=2000, blank=True)

    model = models.CharField(max_length=200, blank=True)
    price = models.CharField(max_length=50, blank=True)
    fuel_type = models.CharField(max_length=50, blank=True)
    mileage = models.CharField(max_length=50, blank=True)
    colour = models.CharField(max_length=50, blank=True)

    source_url = models.URLField(unique=True)

    timestamp = models.DateTimeField(auto_now=True)

    local_image = models.ImageField(upload_to=local_path, null=True)

    def __str__(self):
        return self.title

    def fetch_cover_image(self):
        parsed_url = urlparse(self.cover_img_url)
        name, type = splitext(basename(parsed_url.path))

        # Very simple checking of extensions.
        # TODO: check for (png|jpg|jpeg|gif)
        try:
            assert(type)
        except:
            return "Image format error.."

        new_name = str(uuid4()) + type
        tmp_path = os.path.join("/tmp", new_name)

        # Download file.
        with open(tmp_path, "wb") as buff:
            try:
                resp = requests.get(self.cover_img_url)
                buff.write(resp.content)
            except MissingSchema:
                return "downloading error"

        # Delete old file if exists.
        if self.local_image:
            self.local_image.delete()

        # Upload to django.
        buff = File(open(tmp_path, 'rb'))
        self.local_image.save(new_name, buff)

        # Clean up (maybe delete odl).
        os.remove(tmp_path)

        return "ok"

motors/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Motor


def motors_list(request):
    records = Motor.objects.order_by("-timestamp")
    paginator = Paginator(records, 12)

    page = request.GET.get('page')
    try:
        records = paginator.page(page)

    except PageNotAnInteger:    # Display first page when wrong argument.
        records = paginator.page(1)

    except EmptyPage:   # Display last page.
        records = paginator.page(paginator.num_pages)

    return render(request, "motors/list.html", {"records": records})


def show_item(request, item_pk):
    item = get_object_or_404(Motor, pk=item_pk)
    return render(request, "motors/item.html", {"item": item})

motors/templates/motors/item.html
{% extends 'shoutboard/base.html' %}
{% load static %}


{# block bootstrap3_content %}
    <h3>{{ item.title }}</h3>
    <img src="{{ item.local_image.url }}"/>
    <p>{{ item.description }}</p>
    <p>{{ item.model }}</p>
    <p>{{ item.price }}</p>
    <p>{{ item.fiel_type }}</p>
    <p>{{ item.mileage }}</p>
    <p>{{ item.colour }}</p>
    <p>{{ item.timestamp }}</p>
    <p>{{ item.source_url }}</p>
{% endblock #}

{% block bootstrap3_extra_head %}
    <link rel="stylesheet" href="{% static 'motors/css/item_style.css' %}" type="text/css" />
{% endblock %}

{% block bootstrap3_content %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="{% url 'motors:motors_list' %}">Motors</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1>{{ item.title }}</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>Scraped: <span class="glyphicon glyphicon-time"></span> {{ item.timestamp }}</p>

                <hr>

                <!-- Preview Image -->
                <!--img class="img-responsive" src="http://placehold.it/900x300" alt=""-->
                <img class="img-responsive" src="{{ item.local_image.url }}" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">{{ item.description }}</p>

                <p>Model: {{ item.model }}</p>
                <p>Price: {{ item.price }}</p>
                <p>Fuel type: {{ item.fiel_type }}</p>
                <p>Mileage: {{ item.mileage }}</p>
                <p>Colour: {{ item.colour }}</p>
                <p>Source: {{ item.source_url }}</p>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->
{% endblock %}

motors/templates/motors/list.html
{% extends 'shoutboard/base.html' %}
{% load static %}

{% block bootstrap3_extra_head %}
    <link rel="stylesheet" href="{% static 'motors/css/list_style.css' %}" type="text/css" />
{% endblock %}

{% block bootstrap3_content %}
   <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Page Heading
                    <small>Secondary Text</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            {% for record in records %}
            <div class="col-md-4 portfolio-item">
                <a href="{% url 'motors:show_item' record.pk %}">
                    <!--img class="img-responsive" src="http://placehold.it/700x400" alt=""-->
                    <img class="img-responsive" src="{{ record.local_image.url }}" alt="" />
                </a>
                <h4>
                    <a href="{% url 'motors:show_item' record.pk %}">{{ record.title }}</a>
                </h4>
                <p>Current description is too long for this filed or need to use libraries like jQuery dotdot</p>
            </div>
                {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
                {% endif %} 

            {% endfor %}
        </div>

        <hr>

        <!-- Pagination -->
        <!--div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div-->
        <!-- /.row -->
        <div class="row text-center">
            <div class="col-lg-12">
                <div class="pagination">
                    <span class="step-links">
                        {% if records.has_previous %}
                            <a href="?page={{ records.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ records.number }} of {{ records.paginator.num_pages }}.
                        </span>

                        {% if records.has_next %}
                            <a href="?page={{ records.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <!--script src="js/jquery.js"></script-->

    <!-- Bootstrap Core JavaScript -->
    <!--script src="js/bootstrap.min.js"></script-->

{% endblock %}