_auth/urls.py
from django.conf.urls import url

from . import views

app_name = "_auth"

urlpatterns = [
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^signup$', views.SignUp.as_view(), name='signup'),
    url(r'^activate/(?P<hash>.+)$', views.activate_user, name='activate'),

    url(r'^password-reset$', views.Reset.as_view(), name='password-reset'),
    url(r'^confirm-password-reset/(?P<hash>.+)$', views.ConfirmReset.as_view(),
        name='confirm-password-reset')
]

_profile/urls.py
from django.conf.urls import url
from . import views

app_name = "_profile"

urlpatterns = [
    url(r'^$', views.Profile.as_view(), name='profile_index'),
    url(r'password$', views.ProfilePassword.as_view(),
        name='profile_password'),
    url(r'address$', views.ProfileAddress.as_view(),
        name='profile_address'),

    url(r'avatar$', views.ProfileAvatar.as_view(),
        name='profile_avatar'),

    url(r'company$', views.ProfileCompany.as_view(),
        name='profile_company'),
]

shoutboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),

    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1.0/', include(router.urls))

    # Auth in api web view.
    # url(r'^api/v1.0/auth', include("rest_framework.urls",
    #                                  namespace="rest_framework")),

    url(r'^api/v1.0/', include('api_1_0.urls')),
    url(r'^motors/', include('motors.urls')),
    url(r'^auth/', include('_auth.urls')),

    url(r'^profile/', include('_profile.urls'))
]

_profile/models.py
from django.db import models
from django.contrib.auth.models import User
import hashlib
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    class Meta:
        db_table = "profile"

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    company_name = models.CharField(max_length=100, blank=True)
    vat_number = models.CharField(max_length=100, blank=True)

    address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    post_code = models.CharField(max_length=50, blank=True)

    @property
    def gravatar(self):
        hash = hashlib.md5(self.user.email.encode('utf-8')).hexdigest()
        url = "https://gravatar.com/avatar/{}".format(hash)
        return url


@receiver(post_save, sender=User)
def save_user(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

_profile/forms.py
from django import forms
from django.forms import CharField, PasswordInput, TextInput, Textarea
import re


class ChangePasswordForm(forms.Form):
    def __init__(self, user=None, data=None):
        self.user = user
        super(ChangePasswordForm, self).__init__(data=data)

    cur_password = CharField(label="Current password", min_length=10,
                             widget=PasswordInput(attrs={
                                                  'placeholder': 'Current password:',
                                                  'class': 'form-control'}))

    new_password = CharField(label="New password", min_length=10,
                             widget=PasswordInput(attrs={
                                                  'placeholder': 'New password:',
                                                  'class': 'form-control'}))

    confirm = CharField(label="Confirm", min_length=10,
                        widget=PasswordInput(attrs={
                                             'placeholder': 'Confirm:',
                                             'class': 'form-control'}))

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        cur_password = cleaned_data['cur_password']
        if not self.user.check_password(cur_password):
            raise forms.ValidationError("Wrong current password")

        new_password = cleaned_data['new_password']
        confirm = cleaned_data['confirm']

        # Check for numbers in new password.
        if not re.search("\d+", new_password):
            raise forms.ValidationError("New password must contain a number")

        if new_password != confirm:
            raise forms.ValidationError("Passwords not match")


class ChangeAddressForm(forms.Form):
    address = CharField(label='Address', required=False,
                        widget=Textarea(attrs={
                                        'class': 'form-control',
                                        'placeholder': 'Address',
                                        'autofocus': 'autofocus',
                                        'rows': 5}))

    city = CharField(label='City:', required=False,
                     widget=TextInput(attrs={
                                      'class': 'form-control',
                                      'placeholder': 'City'}))

    country = CharField(label='Country:', required=False,
                        widget=TextInput(attrs={
                                         'class': 'form-control',
                                         'placeholder': 'Country'}))

    post_code = CharField(label='Postal Code:', required=False,
                          widget=TextInput(attrs={
                                           'class': 'form-control',
                                           'placeholder': 'Postal code'}))


class ChangeCompanyForm(forms.Form):
    company_name = CharField(label='Company name:', required=False,
                             widget=TextInput(attrs={
                                              'class': 'form-control',
                                              'placeholder': 'Company'}))

    vat_number = CharField(label='VAT Number:', required=False,
                           widget=TextInput(attrs={
                                            'class': 'form-control',
                                            'placeholder': 'VAT'}))

_profile/views.py
from django.shortcuts import render
from django.views import View
# from django.urls import reverse
# from django.http import HttpResponseRedirect

from .forms import ChangePasswordForm, ChangeAddressForm, ChangeCompanyForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from _profile.models import Profile as UserProfile


class Profile(LoginRequiredMixin, View):
    login_url = "/auth/login"

    def get(self, request):
        context = {"user": request.user}
        return render(request, "profile/index.html", context)


class ProfilePassword(LoginRequiredMixin, View):
    login_url = "/auth/login"

    def get(self, request):
        form = ChangePasswordForm()
        context = {
            "user": request.user,
            "form": form,
        }
        return render(request, "profile/password.html", context)

    def post(self, request):
        user = request.user
        form = ChangePasswordForm(data=request.POST, user=user)

        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password updated")
            return redirect(reverse("_profile:profile_password"))

        context = {
            "user": request.user,
            "form": form,
        }

        return render(request, "profile/password.html", context)


class ProfileAddress(LoginRequiredMixin, View):
    login_url = "/auth/login"

    def get(self, request):
        profile = UserProfile.objects.get(user__username=request.user.username)

        form = ChangeAddressForm(initial={
                                 'address': profile.address,
                                 'city': profile.city,
                                 'country': profile.country,
                                 'post_code': profile.post_code,
                                 })
        return render(request, "profile/address.html", {"form": form})

    def post(self, request):
        profile = UserProfile.objects.get(user__username=request.user.username)
        form = ChangeAddressForm(request.POST)

        if form.is_valid():
            profile.address = form.cleaned_data['address']
            profile.city = form.cleaned_data['city']
            profile.country = form.cleaned_data['country']
            profile.post_code = form.cleaned_data['post_code']
            profile.save()

            messages.success(request, "Address updated")
            return redirect(reverse("_profile:profile_address"))

        return render(request, "profile/address.html", {"form": form})


class ProfileAvatar(LoginRequiredMixin, View):
    login_url = "/auth/login"

    def get(self, request):
        return render(request, "profile/avatar.html", {})


class ProfileCompany(LoginRequiredMixin, View):
    login_url = "/auth/login"

    def get(self, request):
        profile = UserProfile.objects.get(user__username=request.user.username)
        form = ChangeCompanyForm(initial={
                                 'company_name': profile.company_name,
                                 'vat_number': profile.vat_number,
                                 })
        return render(request, "profile/company.html", {"form": form})

    def post(self, request):
        profile = UserProfile.objects.get(user__username=request.user.username)
        form = ChangeCompanyForm(request.POST)

        if form.is_valid():
            profile.company_name = form.cleaned_data['company_name']
            profile.vat_number = form.cleaned_data['vat_number']
            profile.save()

            messages.success(request, "Updated")
            return redirect(reverse("_profile:profile_company"))

        return render(request, "profile/company.html", {"form": form})

_profile/templates/profile/address.html
{% extends "profile/base.html" %}

{% block bootstrap3_title %}Address{% endblock %}

{% block address_active %}active{% endblock %}

{% block bootstrap3_extra_head %}
    {{ block.super }}
    <style>
        #submit_btn {
            margin-top:10px;
        }
    </style>
{% endblock %}

{% block profile_page %}
    <div class="col-lg-5">

        <h3>Billing Address</h3>
        <hr>

        <form method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}

            {% for field in form %}
                <label for="{{ field.name }}">{{ field.label }}</label>
                {{ field }}

                {% if field.errors %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endfor %}

            <button id="submit_btn" class="btn btn-primary" type="submit">Change</button>
        </form>
    </div>
{% endblock %}

_profile/templates/profile/avatar.html
{% extends "profile/base.html" %}

{% block bootstrap3_title %}Avatar{% endblock %}

{% block avatar_active %}active{% endblock %}

{% block profile_page %}
    <h3>Avatar</h3>
    <hr>
    <p>Change your avatar on: <a target="_blank" href="https://signup.wordpress.com/signup/?ref=oauth2&oauth2_redirect=08e76c0d1951129d540ca2737b5aec9f%40https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3Dddd55f70e93fc5346f73784622ddf5f2a9e0a72cf155d233411631db83e74220%26redirect_uri%3Dhttps%253A%252F%252Fen.gravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login&wpcom_connect=1">gravatar.com</a>
{% endblock %}

_profile/templates/profile/base.html
{% extends "shoutboard/base.html" %}
{% load static %}

{% block bootstrap3_extra_head %}
    <link href="{% static 'profile/css/font-awesome.min.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'profile/css/sb-admin.css' %}" type="text/css" rel="stylesheet" />

    <style>
        #alerts {
            position:fixed;
            z-index:9999;
            top:5px;
            width:350px;
        }
    </style>

{% endblock %}

{% block bootstrap3_title %}Profile{% endblock %}

{% block bootstrap3_content %}
    <div id="alerts">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <!--li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li-->

                    <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SB Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user.username}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url '_profile:profile_index' %}"><i class="fa fa-fw fa-user"></i>Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url '_auth:logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="{% block index_active %}{% endblock %}">
                        <a href="{% url '_profile:profile_index' %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li class="{% block password_active %}{% endblock %}">
                        <a href="{% url '_profile:profile_password' %}"><i class="fa fa-fw fa-bar-chart-o"></i> Password</a>
                    </li>
                    <li class="{% block address_active %}{% endblock %}">
                        <a href="{% url '_profile:profile_address' %}"><i class="fa fa-fw fa-table"></i> Address</a>
                    </li>
                    <li class="{% block avatar_active %}{% endblock %}">
                        <a href="{% url '_profile:profile_avatar' %}"><i class="fa fa-fw fa-edit"></i> Avatar</a>
                    </li>
                    <li class="{% block company_active %}{% endblock %}">
                        <a href="{% url '_profile:profile_company' %}"><i class="fa fa-fw fa-desktop"></i> Company</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-wrench"></i> Payment</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                {% block profile_page %}content{% endblock %}
                
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
{% endblock %}

_profile/templates/profile/company.html
{% extends "profile/base.html" %}

{% block bootstrap3_title %}Company{% endblock %}

{% block company_active %}active{% endblock %}

{% block bootstrap3_extra_head %}
    {{ block.super }}
    <style>
        #submit_btn {
            margin-top:10px;
        }
    </style>
{% endblock %}

{% block profile_page %}
    <div class="col-lg-5">

        <h3>Company</h3>
        <hr>

        <form method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}

            {% for field in form %}
                <label for="{{ field.name }}">{{ field.label }}</label>

                {{ field }}

                {% if field.errors %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endfor %}

            <button id="submit_btn" class="btn btn-primary" type="submit">Change</button>
        </form>
    </div>
{% endblock %}

_profile/templates/profile/index.html
{% extends "profile/base.html" %}

{% block bootstrap3_title %}Profile overview{% endblock %}

{% block index_active %}active{% endblock %}

{% block profile_page %}
    <div class="media">
        <div class="media-left media-bottom">
            <a href="#">
                <img class="media-object" src="{{ user.profile.gravatar }}" alt="">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{ user.first_name|capfirst|default:"Name" }} {{ user.last_name|capfirst|default:"Surname" }}</h4>
            <h6>{{ user.email }}</h6>
            <!--p class="lead">{{ user.profile.company_name|capfirst|default:"Company name" }}</p-->
            <h4>{{ user.profile.company_name|capfirst|default:"Company name" }}</h4>
        </div>
    </div>
    <hr>

    <div class="col-lg-5">
    <div class="panel panel-default">
        <div class="panel-body">
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Address: {{ user.profile.address }}</p>
            <p>Company: {{ user.profile.company_name }}</p>
            <p>VAT number: {{ user.profile.vat_number }}</p>
        </div>
    </div>
    </div>
{% endblock %}

_profile/templates/profile/password.html
{% extends "profile/base.html" %}

{% block bootstrap3_title %}Profile overview{% endblock %}

{% block password_active %}active{% endblock %}

{% block bootstrap3_extra_head %}
    {{ block.super }}
    <style>
        #submit_btn {
            margin-top:10px;
        }
    </style>
{% endblock %}

{% block profile_page %}
    <div class="col-lg-5">

        <h3>Change password</h3>
        <hr>

        <form method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}

            {% for field in form %}
                <label for="{{ field.name }}">{{ field.label }}</label>
                {{ field }}

                {% if field.errors %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endfor %}

            <button id="submit_btn" class="btn btn-primary" type="submit">Change</button>
        </form>
    </div>
{% endblock %}